/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/include.file" instead.
 */

#include <check.h>
#include <complex.h>
#include <float.h>
#include <math.h>

#include "src/helpers/quadeq_helpers.h"
#include "src/quadratic_equation.h"

START_TEST(check_accuracy_errors_loop) {
  char accuracy[] =
      "abceghjkmnopqrstuvwxyABCEGHJKMNOPQRSTUVWXY "
      "!\"#$%%&'()*+,-./:;<=>?@[]^_`{|}~\\\t\n\r";
  Accuracy epsilon;
  for (char *p = accuracy; *p != '\0'; ++p) {
    ck_assert(check_accuracy(p, &epsilon) == 0);
  }
}
END_TEST

START_TEST(check_accuracy_errors_plus) {
  char accuracy[] = "+";
  Accuracy epsilon;
  ck_assert(check_accuracy(accuracy, &epsilon) == 0);
}
END_TEST

START_TEST(check_accuracy_errors_minus) {
  char accuracy[] = "-";
  Accuracy epsilon;
  ck_assert(check_accuracy(accuracy, &epsilon) == 0);
}
END_TEST

START_TEST(check_accuracy_letter_i) {
  char accuracy[] = "i";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(check_accuracy_letter_I) {
  char accuracy[] = "I";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(check_accuracy_letter_f) {
  char accuracy[] = "f";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'f');
}
END_TEST

START_TEST(check_accuracy_letter_F) {
  char accuracy[] = "F";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'f');
}
END_TEST

START_TEST(check_accuracy_letter_d) {
  char accuracy[] = "d";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'd');
}
END_TEST

START_TEST(check_accuracy_letter_D) {
  char accuracy[] = "D";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'd');
}
END_TEST

START_TEST(check_accuracy_letter_l) {
  char accuracy[] = "l";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_letter_L) {
  char accuracy[] = "L";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_letter_z) {
  char accuracy[] = "z";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'z');
}
END_TEST

START_TEST(check_accuracy_letter_Z) {
  char accuracy[] = "Z";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'z');
}
END_TEST

START_TEST(check_accuracy_letter_empty_string) {
  char accuracy[] = "";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_letter_NULL) {
  char *accuracy = NULL;
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_number_0) {
  char accuracy[] = "0";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(check_accuracy_number_PLUS0) {
  char accuracy[] = "+0";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(check_accuracy_number_MINUS0) {
  char accuracy[] = "-0";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(check_accuracy_number_1) {
  char accuracy[] = "1";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 1);
}
END_TEST

START_TEST(check_accuracy_number_PLUS2) {
  char accuracy[] = "+2";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 2);
}
END_TEST

START_TEST(check_accuracy_number_MINUS3) {
  char accuracy[] = "-3";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -3);
}
END_TEST

START_TEST(check_accuracy_number_45) {
  char accuracy[] = "45";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 45);
}
END_TEST

START_TEST(check_accuracy_number_PLUS98) {
  char accuracy[] = "+98";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 98);
}
END_TEST

START_TEST(check_accuracy_number_MINUS67) {
  char accuracy[] = "-67";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -67);
}
END_TEST

START_TEST(check_accuracy_number_111) {
  char accuracy[] = "111";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 111);
}
END_TEST

START_TEST(check_accuracy_number_PLUS308) {
  char accuracy[] = "+308";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 308);
}
END_TEST

START_TEST(check_accuracy_number_MINUS940) {
  char accuracy[] = "-940";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -940);
}
END_TEST

START_TEST(check_accuracy_number_2000) {
  char accuracy[] = "2000";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 2000);
}
END_TEST

START_TEST(check_accuracy_number_PLUS1006) {
  char accuracy[] = "+1006";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 1006);
}
END_TEST

START_TEST(check_accuracy_number_MINUS3597) {
  char accuracy[] = "-3597";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -3597);
}
END_TEST

START_TEST(check_accuracy_number_MAX) {
  char accuracy[] = "4932";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 4932);
}
END_TEST

START_TEST(check_accuracy_number_PLUS_MAX) {
  char accuracy[] = "+4932";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 4932);
}
END_TEST

START_TEST(check_accuracy_number_MINUS_MAX) {
  char accuracy[] = "-4932";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -4932);
}
END_TEST

START_TEST(check_accuracy_number_MORE_MAX) {
  char accuracy[] = "4933";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_number_MINUS_MORE_MAX) {
  char accuracy[] = "-4933";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'z');
}
END_TEST

START_TEST(check_accuracy_number_MORE_DIGITS) {
  char accuracy[] = "10000";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_number_MINUS_MORE_DIGITS) {
  char accuracy[] = "-246712";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'z');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_i) {
  char accuracy[] = "ite4s";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_I) {
  char accuracy[] = "I34g";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_f) {
  char accuracy[] = "fi";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'f');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_F) {
  char accuracy[] = "F.019";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'f');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_d) {
  char accuracy[] = "d+8";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'd');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_D) {
  char accuracy[] = "D 6578";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'd');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_l) {
  char accuracy[] = "l\n";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_L) {
  char accuracy[] = "L-5";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_z) {
  char accuracy[] = "zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'z');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_Z) {
  char accuracy[] = "Zoom";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'z');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_number_and_char_test1) {
  char accuracy[] = "4L";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 4);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_number_and_char_test2) {
  char accuracy[] = "-87f";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -87);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_number_and_char_test3) {
  char accuracy[] = "+399d";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 399);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_number_and_char_test4) {
  char accuracy[] = "-1845Z";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -1845);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_big_number_and_char) {
  char accuracy[] = "39977i";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == TYPE_PRECISION);
  ck_assert(epsilon.value.precision == 'l');
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_number_and_point) {
  char accuracy[] = "-75.98";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, -75);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_number_and_plus) {
  char accuracy[] = "+2+8";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 2);
}
END_TEST

START_TEST(check_accuracy_doubtful_but_ok_number_and_minus) {
  char accuracy[] = "0-8";
  Accuracy epsilon;
  int res = check_accuracy(accuracy, &epsilon);
  ck_assert(res == 1);
  ck_assert(epsilon.type == NUMBER_PRECISION);
  ck_assert_int_eq(epsilon.value.ten_power, 0);
}
END_TEST

START_TEST(ascertain_equation_case_error_a_is_nan) {
  long double a = NAN;
  long double b = 1;
  long double c = 2;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_b_is_nan) {
  long double a = 1;
  long double b = NAN;
  long double c = 2;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_c_is_nan) {
  long double a = 1;
  long double b = 2;
  long double c = NAN;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_a_is_inf) {
  long double a = INFINITY;
  long double b = 1;
  long double c = 2;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_b_is_inf) {
  long double a = 1;
  long double b = INFINITY;
  long double c = 2;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_c_is_inf) {
  long double a = 1;
  long double b = 2;
  long double c = INFINITY;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_a_is_minus_inf) {
  long double a = -INFINITY;
  long double b = 1;
  long double c = 2;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_b_is_minus_inf) {
  long double a = 1;
  long double b = -INFINITY;
  long double c = 2;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_c_is_minus_inf) {
  long double a = 1;
  long double b = 2;
  long double c = -INFINITY;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_ab_not_finite) {
  long double a = INFINITY;
  long double b = -INFINITY;
  long double c = 2;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_ac_not_finite) {
  long double a = NAN;
  long double b = 3;
  long double c = -INFINITY;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_bc_not_finite) {
  long double a = -2;
  long double b = NAN;
  long double c = NAN;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_error_all_not_finite) {
  long double a = -INFINITY;
  long double b = INFINITY;
  long double c = INFINITY;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ERROR_INPUT);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_abc) {
  long double a = 0;
  long double b = 0;
  long double c = 0;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_ABC);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_ab_test1) {
  long double a = 0;
  long double b = 0;
  long double c = -5.4;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_AB);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_ab_test2) {
  long double a = 0;
  long double b = 0;
  long double c = 857;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_AB);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_ac) {
  long double a = 0;
  long double b = 8464.555;
  long double c = 0;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_A);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_a) {
  long double a = 0;
  long double b = 643;
  long double c = 23.1;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_A);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_b_test_1) {
  long double a = -8115;
  long double b = 0;
  long double c = 45453.55444;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_B);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_b_test_2) {
  long double a = 0.00075;
  long double b = 0;
  long double c = 7777;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_B);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_c_test_1) {
  long double a = -0.00001;
  long double b = -0.0004;
  long double c = 0;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_C);
}
END_TEST

START_TEST(ascertain_equation_case_zeros_c_test_2) {
  long double a = 1.23456;
  long double b = -6666;
  long double c = 0;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == ZERO_C);
}
END_TEST

START_TEST(ascertain_equation_case_usual_test1) {
  long double a = 2;
  long double b = 3;
  long double c = 4;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == USUAL);
  ck_assert_ldouble_eq(bb, 9);
  ck_assert_ldouble_eq(ac4, 32);
}
END_TEST

START_TEST(ascertain_equation_case_usual_test2) {
  long double a = 57892;
  long double b = -0.0625;
  long double c = -9.125;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == USUAL);
  ck_assert_ldouble_eq(bb, 0.00390625L);
  ck_assert_ldouble_eq(ac4, -2113058);
}
END_TEST

START_TEST(ascertain_equation_case_usual_test3) {
  long double a = -1e100L;
  long double b = 1e-100L;
  long double c = 4e200L;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == USUAL);
  ck_assert_ldouble_eq_tol(bb, 1e-200L, 1e-212L);
  ck_assert_ldouble_eq_tol(ac4, -1.6e301L, 1e289L);
}
END_TEST

START_TEST(ascertain_equation_case_usual_test4) {
  long double a = -5e-2000L;
  long double b = -7e415L;
  long double c = -4e200L;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == USUAL);
  ck_assert_ldouble_eq_tol(bb, 4.9e831L, 1e819L);
  ck_assert_ldouble_eq_tol(ac4, 8e-1799L, 1e-1787L);
}
END_TEST

START_TEST(ascertain_equation_case_small_discriminant) {
  long double a = 1e-2000L;
  long double b = 1e-2467L;
  long double c = 1e-2933L;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == SMALL_BB_AND_AC4);
}
END_TEST

START_TEST(ascertain_equation_case_big_discriminant_bb_and_ac4) {
  long double a = 1e2000L;
  long double b = 1e2467L;
  long double c = 1e2932L;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == BIG_BB_AND_AC4);
}
END_TEST

START_TEST(ascertain_equation_case_big_discriminant_bb) {
  long double a = 1e200L;
  long double b = -1e2467L;
  long double c = 1e293L;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == BIG_BB);
}
END_TEST

START_TEST(ascertain_equation_case_big_discriminant_ac4) {
  long double a = -1e2000L;
  long double b = 1e246L;
  long double c = 1e2932L;
  long double bb, ac4;
  EquationCases result = ascertain_equation_case(a, b, c, &bb, &ac4);
  ck_assert(result == BIG_AC4);
}
END_TEST

START_TEST(errors_a_is_nan) {
  long double a = NAN;
  long double b = 1;
  long double c = 2;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_b_is_nan) {
  long double a = 1;
  long double b = NAN;
  long double c = 2;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_c_is_nan) {
  long double a = 1;
  long double b = 2;
  long double c = NAN;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_a_is_inf) {
  long double a = INFINITY;
  long double b = 1;
  long double c = 2;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_b_is_inf) {
  long double a = 1;
  long double b = INFINITY;
  long double c = 2;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_c_is_inf) {
  long double a = 1;
  long double b = 2;
  long double c = INFINITY;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_a_is_minus_inf) {
  long double a = -INFINITY;
  long double b = 1;
  long double c = 2;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_b_is_minus_inf) {
  long double a = 1;
  long double b = -INFINITY;
  long double c = 2;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_c_is_minus_inf) {
  long double a = 1;
  long double b = 2;
  long double c = -INFINITY;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_ab_not_finite) {
  long double a = NAN;
  long double b = INFINITY;
  long double c = 2;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_ac_not_finite) {
  long double a = -INFINITY;
  long double b = 3;
  long double c = NAN;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_bc_not_finite) {
  long double a = -2;
  long double b = INFINITY;
  long double c = INFINITY;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_all_not_finite) {
  long double a = NAN;
  long double b = NAN;
  long double c = -INFINITY;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_bad_accuracy_char) {
  long double a = 1;
  long double b = 2;
  long double c = 1;
  char accuracy[] = "q";
  EquationRoots result = SOLVE_EQUATION(a, b, c, accuracy);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_bad_accuracy_string) {
  long double a = 1;
  long double b = 2;
  long double c = 1;
  char accuracy[] = "two";
  EquationRoots result = SOLVE_EQUATION(a, b, c, accuracy);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_bad_accuracy_minus_first) {
  long double a = 1;
  long double b = 2;
  long double c = 1;
  char accuracy[] = "-f";
  EquationRoots result = SOLVE_EQUATION(a, b, c, accuracy);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(errors_bad_accuracy_plus_first) {
  long double a = 1;
  long double b = 2;
  long double c = 1;
  char accuracy[] = "+d";
  EquationRoots result = SOLVE_EQUATION(a, b, c, accuracy);
  ck_assert(result.rootsNumber == InvalidValue);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(without_roots_all_zero) {
  long double a = 0;
  long double b = 0;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == InfinityRoots);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(without_roots_c_not_zero_test1) {
  long double a = 0;
  long double b = 0;
  long double c = 1;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == NoRoots);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(without_roots_c_not_zero_test2) {
  long double a = 0;
  long double b = 0;
  long double c = -5.7;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == NoRoots);
  ck_assert_ldouble_nan(crealf(result.root1));
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(only_one_root_c_zero) {
  long double a = 0;
  long double b = -1.7;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OnlyOneRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(only_one_root_precise_value_1) {
  long double a = 0;
  long double b = 4;
  long double c = 6;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OnlyOneRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -1.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(only_one_root_precise_value_2) {
  long double a = 0;
  long double b = -0.385;
  long double c = 0.2578125L;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OnlyOneRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.6875);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(only_one_root_approximately_value_1) {
  long double a = 0;
  long double b = 3;
  long double c = -1;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OnlyOneRoot);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 0.3333333333333333333L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(only_one_root_approximately_value_2) {
  long double a = 0;
  long double b = -1.45;
  long double c = -1.678;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OnlyOneRoot);
  ck_assert_ldouble_eq_tol(crealf(result.root1), -1.1572413793103448276L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_nan(crealf(result.root2));
}
END_TEST

START_TEST(incomplete_equation_b0_real_precise_value_1) {
  long double a = 3;
  long double b = 0;
  long double c = -4.6875;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -1.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 1.25);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(incomplete_equation_b0_real_precise_value_2) {
  long double a = -1.75;
  long double b = 0;
  long double c = 3.0146484375L;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -1.3125);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 1.3125);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(incomplete_equation_b0_real_approximately_value) {
  long double a = 1;
  long double b = 0;
  long double c = -3;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), -1.7320508075688772935L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root2), 1.7320508075688772935L,
                           LDBL_EPSILON);
}
END_TEST

START_TEST(incomplete_equation_b0_complex_precise_value_1) {
  long double a = 0.00390625L;
  long double b = 0;
  long double c = 0.66015625L;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0);
  ck_assert_ldouble_eq(cimagf(result.root1), -13);
  ck_assert_ldouble_eq(crealf(result.root2), 0);
  ck_assert_ldouble_eq(cimagf(result.root2), 13);
}
END_TEST

START_TEST(incomplete_equation_b0_complex_precise_value_2) {
  long double a = -16.625;
  long double b = 0;
  long double c = -233.7890625L;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0);
  ck_assert_ldouble_eq(cimagf(result.root1), -3.75);
  ck_assert_ldouble_eq(crealf(result.root2), 0);
  ck_assert_ldouble_eq(cimagf(result.root2), 3.75);
}
END_TEST

START_TEST(incomplete_equation_b0_complex_approximately_value) {
  long double a = -9;
  long double b = 0;
  long double c = -1;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0);
  ck_assert_ldouble_eq_tol(cimagf(result.root1), -0.3333333333333333333L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(crealf(result.root2), 0);
  ck_assert_ldouble_eq_tol(cimagf(result.root2), 0.3333333333333333333L,
                           LDBL_EPSILON);
}
END_TEST

START_TEST(incomplete_equation_c0_precise_value_1) {
  long double a = 1.75;
  long double b = 3.5;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 0);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(incomplete_equation_c0_precise_value_2) {
  long double a = 3.5;
  long double b = -1.75;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 0.5);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(incomplete_equation_c0_precise_value_3) {
  long double a = -0.53125;
  long double b = 2.357421875L;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 4.4375);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(incomplete_equation_c0_precise_value_4) {
  long double a = -76.84375;
  long double b = -461.0625;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -6);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 0);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(incomplete_equation_c0_approximately_value_1) {
  long double a = -7;
  long double b = -3;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), -0.4285714285714285714L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 0);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(incomplete_equation_c0_approximately_value_2) {
  long double a = 7;
  long double b = -3;
  long double c = 0;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root2), -0.4285714285714285714L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_one_double_roots_precise_value_1) {
  long double a = 16;
  long double b = -24;
  long double c = 9;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.75);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 0.75);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_one_double_roots_precise_value_2) {
  long double a = -4.25;
  long double b = 6.375;
  long double c = -2.390625;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.75);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 0.75);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_one_double_roots_precise_value_3) {
  long double a = 28;
  long double b = 63;
  long double c = 35.4375;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -1.125);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), -1.125);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_one_double_roots_precise_value_4) {
  long double a = -0.0810546875L;
  long double b = -0.783203125L;
  long double c = -9.8076171875L;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -11);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), -11);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_one_double_roots_approximately_value_1) {
  long double a = 36.75;
  long double b = -31.5;
  long double c = 6.75;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 0.4285714285714285714L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root2), 0.4285714285714285714L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_one_double_roots_approximately_value_2) {
  long double a = 6.75;
  long double b = 31.5;
  long double c = 36.75;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq_tol(crealf(result.root1), -2.3333333333333333333L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root2), -2.3333333333333333333L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_two_real_roots_precise_value_1) {
  long double a = 2097152;
  long double b = -11534336;
  long double c = 5242880;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 5);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_two_real_roots_precise_value_2) {
  long double a = 536870912;
  long double b = -16384;
  long double c = -15;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -0.000152587890625L);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), 0.00018310546875L);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_two_real_roots_precise_value_3) {
  long double a = 262144;
  long double b = 43739946942469.0L;
  long double c = 834273280;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -166854656.0L);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root2), -0.000019073486328125L);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_two_real_roots_approximately_value) {
  long double a = 1;
  long double b = 14;
  long double c = -38;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), -16.3273790530888150456L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root2), 2.327379053088815045554L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root2), 0);
}
END_TEST

START_TEST(exactly_two_complex_roots_precise_value_1) {
  long double a = -0.09375;
  long double b = 0.375;
  long double c = -0.46875;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 2);
  ck_assert_ldouble_eq(cimagf(result.root1), -1);
  ck_assert_ldouble_eq(crealf(result.root2), 2);
  ck_assert_ldouble_eq(cimagf(result.root2), 1);
}
END_TEST

START_TEST(exactly_two_complex_roots_precise_value_2) {
  long double a = -128;
  long double b = -26112;
  long double c = -1331784;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -102);
  ck_assert_ldouble_eq(cimagf(result.root1), -0.75);
  ck_assert_ldouble_eq(crealf(result.root2), -102);
  ck_assert_ldouble_eq(cimagf(result.root2), 0.75);
}
END_TEST

START_TEST(exactly_two_complex_roots_approximately_value_1) {
  long double a = 9;
  long double b = -6;
  long double c = 19;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 0.3333333333333333333L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq_tol(cimagf(result.root1), -1.4142135623730950488L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq_tol(crealf(result.root2), 0.3333333333333333333L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq_tol(cimagf(result.root2), 1.4142135623730950488L,
                           LDBL_EPSILON);
}
END_TEST

START_TEST(exactly_two_complex_roots_approximately_value_2) {
  long double a = 3136;
  long double b = 2352;
  long double c = 1017;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -0.375);
  ck_assert_ldouble_eq_tol(cimagf(result.root1), -0.4285714285714285714L,
                           LDBL_EPSILON);
  ck_assert_ldouble_eq(crealf(result.root1), -0.375);
  ck_assert_ldouble_eq_tol(cimagf(result.root2), 0.4285714285714285714L,
                           LDBL_EPSILON);
}
END_TEST

START_TEST(different_accuracy_test1) {
  long double a = 0.1;
  long double b = -0.2;
  long double c = 0.1;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "l");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "L");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "d");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "D");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "f");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "F");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq_tol(crealf(result.root1), 1, LDBL_EPSILON);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "i");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "I");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "z");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "Z");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "1");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(different_accuracy_test2) {
  long double a = 10;
  long double b = 40;
  long double c = -210;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "l");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "L");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "d");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "D");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "f");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "F");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "i");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "I");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "z");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "Z");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -7);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-3");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(different_accuracy_test3) {
  long double a = -1;
  long double b = 0.5;
  long double c = -4.0625;
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "l");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "L");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "d");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "D");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "f");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "F");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "i");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "I");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "z");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-1");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), -2);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 2);
  result = SOLVE_EQUATION(a, b, c, "-2");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(large_values_bb_and_ac4_two_real_roots) {
  long double a = 1e2500L;
  long double b = -1e2500L;
  long double c = -6e2500L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == BIG_BB_AND_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2500");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2501");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(large_values_bb_and_ac4_two_complex_roots) {
  long double a = 1e2469L;
  long double b = 4e2469L;
  long double c = 13e2469L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == BIG_BB_AND_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), -3);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 3);
  result = SOLVE_EQUATION(a, b, c, "-2469");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), -3);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 3);
  result = SOLVE_EQUATION(a, b, c, "-2470");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(large_values_bb_and_ac4_one_double_root) {
  long double a = 16e2470L;
  long double b = -8e2470L;
  long double c = 1e2470L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == BIG_BB_AND_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2470");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2471");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(large_values_bb) {
  long double a = 1e2460L;
  long double b = 2999999.9375e2460L;
  long double c = -18750e2460L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == BIG_BB);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -3000000);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.0625);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2466");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -3000000);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.0625);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2467");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -1499999.96875L);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), -1499999.96875L);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(large_values_ac4_two_complex_roots) {
  long double a = 1e2465L;
  long double b = 1e2465L;
  long double c = 1000001e2465L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == BIG_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), -1000);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 1000);
  result = SOLVE_EQUATION(a, b, c, "-2469");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), -1000);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 1000);
  result = SOLVE_EQUATION(a, b, c, "-2470");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(large_values_ac4_two_real_roots) {
  long double a = 1e2465L;
  long double b = 1e2465L;
  long double c = -1001000e2465L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == BIG_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2471");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 1);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "-2472");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -0.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), -0.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(small_values_two_real_roots) {
  long double a = 1e-2500L;
  long double b = -1e-2500L;
  long double c = -6e-2500L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == SMALL_BB_AND_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "2500");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 3);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "2501");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.5);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(small_values_two_complex_roots) {
  long double a = 1e-2469L;
  long double b = 4e-2469L;
  long double c = 13e-2469L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == SMALL_BB_AND_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), -3);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 3);
  result = SOLVE_EQUATION(a, b, c, "2469");
  ck_assert(result.rootsNumber == TwoComplexRoots);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), -3);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 3);
  result = SOLVE_EQUATION(a, b, c, "2470");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), -2);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

START_TEST(small_values_one_double_root) {
  long double a = 16e-2470L;
  long double b = -8e-2470L;
  long double c = 1e-2470L;
  long double bb, ac4;
  ck_assert(ascertain_equation_case(a, b, c, &bb, &ac4) == SMALL_BB_AND_AC4);
  EquationRoots result = SOLVE_EQUATION(a, b, c);
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "2470");
  ck_assert(result.rootsNumber == TwoRealRoots);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  result = SOLVE_EQUATION(a, b, c, "2471");
  ck_assert(result.rootsNumber == OneDoubleRoot);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
  ck_assert_ldouble_eq(crealf(result.root1), 0.25);
  ck_assert_ldouble_eq(cimagf(result.root1), 0);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("check_accuracy_errors");
  TCase *tc1_1 = tcase_create("check_accuracy_errors");
  Suite *s2 = suite_create("check_accuracy_letter");
  TCase *tc2_1 = tcase_create("check_accuracy_letter");
  Suite *s3 = suite_create("check_accuracy_number");
  TCase *tc3_1 = tcase_create("check_accuracy_number");
  Suite *s4 = suite_create("check_accuracy_doubtful_but_ok");
  TCase *tc4_1 = tcase_create("check_accuracy_doubtful_but_ok");
  Suite *s5 = suite_create("ascertain_equation_case_error");
  TCase *tc5_1 = tcase_create("ascertain_equation_case_error");
  Suite *s6 = suite_create("ascertain_equation_case_zeros");
  TCase *tc6_1 = tcase_create("ascertain_equation_case_zeros");
  Suite *s7 = suite_create("ascertain_equation_case_usual");
  TCase *tc7_1 = tcase_create("ascertain_equation_case_usual");
  Suite *s8 = suite_create("ascertain_equation_case_small_discriminant");
  TCase *tc8_1 = tcase_create("ascertain_equation_case_small_discriminant");
  Suite *s9 = suite_create("ascertain_equation_case_big_discriminant");
  TCase *tc9_1 = tcase_create("ascertain_equation_case_big_discriminant");
  Suite *s10 = suite_create("errors");
  TCase *tc10_1 = tcase_create("errors");
  Suite *s11 = suite_create("without_roots");
  TCase *tc11_1 = tcase_create("without_roots");
  Suite *s12 = suite_create("only_one_root");
  TCase *tc12_1 = tcase_create("only_one_root");
  Suite *s13 = suite_create("incomplete_equation");
  TCase *tc13_1 = tcase_create("incomplete_equation");
  Suite *s14 = suite_create("exactly_one_double_roots");
  TCase *tc14_1 = tcase_create("exactly_one_double_roots");
  Suite *s15 = suite_create("exactly_two_real_roots");
  TCase *tc15_1 = tcase_create("exactly_two_real_roots");
  Suite *s16 = suite_create("exactly_two_complex_roots");
  TCase *tc16_1 = tcase_create("exactly_two_complex_roots");
  Suite *s17 = suite_create("different_accuracy");
  TCase *tc17_1 = tcase_create("different_accuracy");
  Suite *s18 = suite_create("large_values");
  TCase *tc18_1 = tcase_create("large_values");
  Suite *s19 = suite_create("small_values");
  TCase *tc19_1 = tcase_create("small_values");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, check_accuracy_errors_loop);
  tcase_add_test(tc1_1, check_accuracy_errors_plus);
  tcase_add_test(tc1_1, check_accuracy_errors_minus);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, check_accuracy_letter_i);
  tcase_add_test(tc2_1, check_accuracy_letter_I);
  tcase_add_test(tc2_1, check_accuracy_letter_f);
  tcase_add_test(tc2_1, check_accuracy_letter_F);
  tcase_add_test(tc2_1, check_accuracy_letter_d);
  tcase_add_test(tc2_1, check_accuracy_letter_D);
  tcase_add_test(tc2_1, check_accuracy_letter_l);
  tcase_add_test(tc2_1, check_accuracy_letter_L);
  tcase_add_test(tc2_1, check_accuracy_letter_z);
  tcase_add_test(tc2_1, check_accuracy_letter_Z);
  tcase_add_test(tc2_1, check_accuracy_letter_empty_string);
  tcase_add_test(tc2_1, check_accuracy_letter_NULL);
  suite_add_tcase(s3, tc3_1);
  tcase_add_test(tc3_1, check_accuracy_number_0);
  tcase_add_test(tc3_1, check_accuracy_number_PLUS0);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS0);
  tcase_add_test(tc3_1, check_accuracy_number_1);
  tcase_add_test(tc3_1, check_accuracy_number_PLUS2);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS3);
  tcase_add_test(tc3_1, check_accuracy_number_45);
  tcase_add_test(tc3_1, check_accuracy_number_PLUS98);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS67);
  tcase_add_test(tc3_1, check_accuracy_number_111);
  tcase_add_test(tc3_1, check_accuracy_number_PLUS308);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS940);
  tcase_add_test(tc3_1, check_accuracy_number_2000);
  tcase_add_test(tc3_1, check_accuracy_number_PLUS1006);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS3597);
  tcase_add_test(tc3_1, check_accuracy_number_MAX);
  tcase_add_test(tc3_1, check_accuracy_number_PLUS_MAX);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS_MAX);
  tcase_add_test(tc3_1, check_accuracy_number_MORE_MAX);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS_MORE_MAX);
  tcase_add_test(tc3_1, check_accuracy_number_MORE_DIGITS);
  tcase_add_test(tc3_1, check_accuracy_number_MINUS_MORE_DIGITS);
  suite_add_tcase(s4, tc4_1);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_i);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_I);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_f);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_F);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_d);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_D);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_l);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_L);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_z);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_Z);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_number_and_char_test1);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_number_and_char_test2);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_number_and_char_test3);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_number_and_char_test4);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_big_number_and_char);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_number_and_point);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_number_and_plus);
  tcase_add_test(tc4_1, check_accuracy_doubtful_but_ok_number_and_minus);
  suite_add_tcase(s5, tc5_1);
  tcase_add_test(tc5_1, ascertain_equation_case_error_a_is_nan);
  tcase_add_test(tc5_1, ascertain_equation_case_error_b_is_nan);
  tcase_add_test(tc5_1, ascertain_equation_case_error_c_is_nan);
  tcase_add_test(tc5_1, ascertain_equation_case_error_a_is_inf);
  tcase_add_test(tc5_1, ascertain_equation_case_error_b_is_inf);
  tcase_add_test(tc5_1, ascertain_equation_case_error_c_is_inf);
  tcase_add_test(tc5_1, ascertain_equation_case_error_a_is_minus_inf);
  tcase_add_test(tc5_1, ascertain_equation_case_error_b_is_minus_inf);
  tcase_add_test(tc5_1, ascertain_equation_case_error_c_is_minus_inf);
  tcase_add_test(tc5_1, ascertain_equation_case_error_ab_not_finite);
  tcase_add_test(tc5_1, ascertain_equation_case_error_ac_not_finite);
  tcase_add_test(tc5_1, ascertain_equation_case_error_bc_not_finite);
  tcase_add_test(tc5_1, ascertain_equation_case_error_all_not_finite);
  suite_add_tcase(s6, tc6_1);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_abc);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_ab_test1);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_ab_test2);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_ac);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_a);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_b_test_1);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_b_test_2);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_c_test_1);
  tcase_add_test(tc6_1, ascertain_equation_case_zeros_c_test_2);
  suite_add_tcase(s7, tc7_1);
  tcase_add_test(tc7_1, ascertain_equation_case_usual_test1);
  tcase_add_test(tc7_1, ascertain_equation_case_usual_test2);
  tcase_add_test(tc7_1, ascertain_equation_case_usual_test3);
  tcase_add_test(tc7_1, ascertain_equation_case_usual_test4);
  suite_add_tcase(s8, tc8_1);
  tcase_add_test(tc8_1, ascertain_equation_case_small_discriminant);
  suite_add_tcase(s9, tc9_1);
  tcase_add_test(tc9_1, ascertain_equation_case_big_discriminant_bb_and_ac4);
  tcase_add_test(tc9_1, ascertain_equation_case_big_discriminant_bb);
  tcase_add_test(tc9_1, ascertain_equation_case_big_discriminant_ac4);
  suite_add_tcase(s10, tc10_1);
  tcase_add_test(tc10_1, errors_a_is_nan);
  tcase_add_test(tc10_1, errors_b_is_nan);
  tcase_add_test(tc10_1, errors_c_is_nan);
  tcase_add_test(tc10_1, errors_a_is_inf);
  tcase_add_test(tc10_1, errors_b_is_inf);
  tcase_add_test(tc10_1, errors_c_is_inf);
  tcase_add_test(tc10_1, errors_a_is_minus_inf);
  tcase_add_test(tc10_1, errors_b_is_minus_inf);
  tcase_add_test(tc10_1, errors_c_is_minus_inf);
  tcase_add_test(tc10_1, errors_ab_not_finite);
  tcase_add_test(tc10_1, errors_ac_not_finite);
  tcase_add_test(tc10_1, errors_bc_not_finite);
  tcase_add_test(tc10_1, errors_all_not_finite);
  tcase_add_test(tc10_1, errors_bad_accuracy_char);
  tcase_add_test(tc10_1, errors_bad_accuracy_string);
  tcase_add_test(tc10_1, errors_bad_accuracy_minus_first);
  tcase_add_test(tc10_1, errors_bad_accuracy_plus_first);
  suite_add_tcase(s11, tc11_1);
  tcase_add_test(tc11_1, without_roots_all_zero);
  tcase_add_test(tc11_1, without_roots_c_not_zero_test1);
  tcase_add_test(tc11_1, without_roots_c_not_zero_test2);
  suite_add_tcase(s12, tc12_1);
  tcase_add_test(tc12_1, only_one_root_c_zero);
  tcase_add_test(tc12_1, only_one_root_precise_value_1);
  tcase_add_test(tc12_1, only_one_root_precise_value_2);
  tcase_add_test(tc12_1, only_one_root_approximately_value_1);
  tcase_add_test(tc12_1, only_one_root_approximately_value_2);
  suite_add_tcase(s13, tc13_1);
  tcase_add_test(tc13_1, incomplete_equation_b0_real_precise_value_1);
  tcase_add_test(tc13_1, incomplete_equation_b0_real_precise_value_2);
  tcase_add_test(tc13_1, incomplete_equation_b0_real_approximately_value);
  tcase_add_test(tc13_1, incomplete_equation_b0_complex_precise_value_1);
  tcase_add_test(tc13_1, incomplete_equation_b0_complex_precise_value_2);
  tcase_add_test(tc13_1, incomplete_equation_b0_complex_approximately_value);
  tcase_add_test(tc13_1, incomplete_equation_c0_precise_value_1);
  tcase_add_test(tc13_1, incomplete_equation_c0_precise_value_2);
  tcase_add_test(tc13_1, incomplete_equation_c0_precise_value_3);
  tcase_add_test(tc13_1, incomplete_equation_c0_precise_value_4);
  tcase_add_test(tc13_1, incomplete_equation_c0_approximately_value_1);
  tcase_add_test(tc13_1, incomplete_equation_c0_approximately_value_2);
  suite_add_tcase(s14, tc14_1);
  tcase_add_test(tc14_1, exactly_one_double_roots_precise_value_1);
  tcase_add_test(tc14_1, exactly_one_double_roots_precise_value_2);
  tcase_add_test(tc14_1, exactly_one_double_roots_precise_value_3);
  tcase_add_test(tc14_1, exactly_one_double_roots_precise_value_4);
  tcase_add_test(tc14_1, exactly_one_double_roots_approximately_value_1);
  tcase_add_test(tc14_1, exactly_one_double_roots_approximately_value_2);
  suite_add_tcase(s15, tc15_1);
  tcase_add_test(tc15_1, exactly_two_real_roots_precise_value_1);
  tcase_add_test(tc15_1, exactly_two_real_roots_precise_value_2);
  tcase_add_test(tc15_1, exactly_two_real_roots_precise_value_3);
  tcase_add_test(tc15_1, exactly_two_real_roots_approximately_value);
  suite_add_tcase(s16, tc16_1);
  tcase_add_test(tc16_1, exactly_two_complex_roots_precise_value_1);
  tcase_add_test(tc16_1, exactly_two_complex_roots_precise_value_2);
  tcase_add_test(tc16_1, exactly_two_complex_roots_approximately_value_1);
  tcase_add_test(tc16_1, exactly_two_complex_roots_approximately_value_2);
  suite_add_tcase(s17, tc17_1);
  tcase_add_test(tc17_1, different_accuracy_test1);
  tcase_add_test(tc17_1, different_accuracy_test2);
  tcase_add_test(tc17_1, different_accuracy_test3);
  suite_add_tcase(s18, tc18_1);
  tcase_add_test(tc18_1, large_values_bb_and_ac4_two_real_roots);
  tcase_add_test(tc18_1, large_values_bb_and_ac4_two_complex_roots);
  tcase_add_test(tc18_1, large_values_bb_and_ac4_one_double_root);
  tcase_add_test(tc18_1, large_values_bb);
  tcase_add_test(tc18_1, large_values_ac4_two_complex_roots);
  tcase_add_test(tc18_1, large_values_ac4_two_real_roots);
  suite_add_tcase(s19, tc19_1);
  tcase_add_test(tc19_1, small_values_two_real_roots);
  tcase_add_test(tc19_1, small_values_two_complex_roots);
  tcase_add_test(tc19_1, small_values_one_double_root);

  srunner_add_suite(sr, s2);
  srunner_add_suite(sr, s3);
  srunner_add_suite(sr, s4);
  srunner_add_suite(sr, s5);
  srunner_add_suite(sr, s6);
  srunner_add_suite(sr, s7);
  srunner_add_suite(sr, s8);
  srunner_add_suite(sr, s9);
  srunner_add_suite(sr, s10);
  srunner_add_suite(sr, s11);
  srunner_add_suite(sr, s12);
  srunner_add_suite(sr, s13);
  srunner_add_suite(sr, s14);
  srunner_add_suite(sr, s15);
  srunner_add_suite(sr, s16);
  srunner_add_suite(sr, s17);
  srunner_add_suite(sr, s18);
  srunner_add_suite(sr, s19);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
